### ISSUE TITLE
Support non-contiguous arrays?

### ISSUE THREAD

**Issue by virtuald** [pthom/cvnp#6]
Is there a technical reason why this isn't supported or is it just you didn't want to implement it? I'd be interested in taking a shot if it's the latter, but wanted to make sure first that I knew what I was getting myself into first.

**Comment by pthom** [comment]
Hi,

Yes, I would like the final user to know that he is binding a non-continuous matrix, so that a copy will happen and performance will drop. If he can solve it on the user-side code, that would be better for the final performance.

However, if you find a way to make it such that it is user choice (that defaults to no), then yes.

For example: 
````cpp
pybind11::array matx_to_nparray(const cv::Matx<_Tp, _rows, _cols>& m, bool share_memory);
````
could accept an additional parameter (bool allow_non_contiguous = false)

And concerning the automatic caster, we need to find a way to make this user-settable.
For info, I did this via a kind of synonym for casters with shared memory (https://github.com/pthom/cvnp/blob/master/cvnp/cvnp_shared_mat.h) but any method that is easy to grasp for the final user might do.

**Comment by pthom** [comment]
(except if you find a way to set the strides in such a way that no additional copy is required)
